language: rust
env:
  global:
    - secure: todo
script:
  - rustc --version
  - cargo --version
  - cargo build --verbose
  - cargo test
  - cargo doc --no-deps
after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
