[package]

name = "striple"
version = "0.0.1"
authors = ["Emeric Chevalier <emericchevalier.pro@gmail.com>"]

[features]
#default = ["public_crypto","public_openssl","cryptoecdsa","opensslrsa","opensslpbkdf2"]
default = ["public_crypto","serialize","public_openssl","cryptoecdsa","opensslrsa","opensslpbkdf2"]
#default = []
serialize = ["rustc-serialize"]
opensslrsa = ["openssl"]
opensslpbkdf2 = ["openssl"]
cryptoecdsa = ["rust-crypto"]
public_crypto = ["uuid","rust-crypto"]
public_openssl = ["uuid","openssl"]

[[example]]
name='genbasestriples'
path = "examples/generate_base.rs"

[[example]]
name='loadbaststriples'
path = "examples/load_base.rs"

[[example]]
name='striple'
path = "examples/striple.rs"





[dependencies]
log = "0.3.1"
lazy_static = "0.1.10"
num = "0.1.24"
rand = "0.3.8"

[dependencies.rustc-serialize]
version = "0.3.14"
optional = true

[dependencies.openssl]
version = "0.6.2"
optional = true

[dependencies.rust-crypto]
version = "0.2.31"
optional = true

[dependencies.uuid]
version = "0.1.17"
optional = true

[dev-dependencies.docopt_macros]
version = "0.6.64"
[dev-dependencies.docopt]
version = "0.6.64"

[dev-dependencies.env_logger]
version = "0.3.0"

